sprint 13 Add controllers
facedolls/java-shareit pull request #1
Opened 2024-04-19 15:37 UTC by facedolls

2024-04-19 17:26 UTC, andrew-larkin requested changes
Привет! Очень хороший старт нового приложения - структурно все выполнено правильно, код достаточно чистый и вообще реализация хорошая. Я оставил много комментов по коду, но не пугайся - если это сделать сейчас, это значительно облегчит нам жизнь в следующих спринтах. Некоторые комменты встречаются по одному разу, но они актуальны для всех подобных ситуаций. Еще важный момент - у тебя упали постман-тесты при сборке. там 2 штуки всего - это говорит о том, что часть функционала сейчас работает не совсем так как ожидается - это нужно поправить в первую очередь.

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
в классах-моделях, которые повторяют таблицы БД, не стоит использовать @Data - она некорректно рассчитывает хэш, из-за этого могут возникнуть некоторые сложности. лучше заменить ее на @Getter, @Setter и т.д.

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Map<Long, Item> items;
по идее, она должна быть private, чтобы мы могли взаимодействовать с коллекцией только посредством публичных методов этого класса

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@AllArgsConstructor
чтобы в конструктор не добавлять ненужные вещи, мы можем поставить над классом @RequiredArgsConstructor и тогда все переменные, помеченные как final, будут автоматом добавляться в неявный конструктор - таким образом будет обеспечено внедрение зависимости. соответственно, поля, которые не final, не будут в этом задействованы

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@Valid @RequestBody ItemDto itemDto, @RequestHeader(OWNER) Long ownerId) {
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.create(itemDto, ownerId));
Для всех методов во всех контроллерах стоит его добавить

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @ResponseBody
эта аннотация уже содержится в @RestController, поэтому ее использование необязательно

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private CheckConsistency check;
check и любую другую доп.логику переносим в сервис. в контроллере должны быть только вызовы методов сервиса и, возможно, логгирование. Таким образом мы следуем принципам SOLID - букве S, если быть точным. Цель контроллеров - маршрутизация запросов, всем остальным занимается уже сервис

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    @Autowired
чтобы не создавать конструкторы, мы можем поставить над классом @RequiredArgsConstructor и тогда все переменные, помеченные как final, будут автоматом добавляться в неявный конструктор - таким образом будет обеспечено внедрение зависимости

2024-04-19 17:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/service/CheckConsistency.java
> +    public boolean isExistUser(Long userId) {
эти методы можно перенести в сервисы пользователя и item. чтобы воспользовать этим функционалом в других сервисах - просто внедряем userService в другой сервис, где нам нужны его публичные методы

2024-04-21 17:57 UTC, facedolls commented on src/main/java/ru/practicum/shareit/service/CheckConsistency.java
> +    public boolean isExistUser(Long userId) {
цикличная зависимость получиться у UserService от ItemService и наоборот, именно для  избежания этого выносил в отдельный сервис

2024-04-21 20:43 UTC, facedolls commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
Подключил библиотеку, тренируюсь на юзерах

2024-04-21 20:56 UTC, andrew-larkin approved these changes
Привет! Очень хорошо, работа принята! по поводу mapStruct - внедряем в сервисы именно интерфейс.

2024-04-22 19:27 UTC, merged

2024-04-23 06:34 UTC, facedolls commented
Поправил, спасибо!