Add bookings
facedolls/java-shareit pull request #2
Opened 2024-05-12 17:11 UTC by facedolls

2024-05-13 15:36 UTC, andrew-larkin requested changes
Привет! Отличная работа, все сделано очень качественно, уже чувствуется опыт) в паре мест поправить и можем двигаться дальше.

2024-05-13 15:36 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    Optional<List<Comment>> findByItem_Id(Long itemId);
для List можно не использовать Optional - если сущности не будут найдены в БД, вернется пустой список

2024-05-13 15:36 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final CommentRepository commentRepository;
внедрять чужие репозитории - не лучшая практика, т.к. нарушается иерархия зависимостей. в сервисы внедряются другие сервисы

2024-05-13 15:36 UTC, andrew-larkin commented on src/main/resources/banner.txt
> +${AnsiColor.GREEN}   ______                ______
круто)

2024-05-14 10:02 UTC, facedolls commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final CommentRepository commentRepository;
Исправил.
Не совсем понял, почему нарушен принцип единой ответственности, я же просто get делал из чужих репозиториев

2024-05-14 16:56 UTC, merged