Add item requests
facedolls/java-shareit pull request #3
Opened 2024-05-23 21:26 UTC by facedolls

2024-05-24 14:38 UTC, andrew-larkin requested changes
Привет! Хорошая реализация и хорошо написанные тесты! Есть несколько моментов, которые нужно поправить, а также обрати внимание на то, что твой проект пока что не особо собирается. Посмотри на гитхабе, там есть ошибки сборки как раз в разделе тестов. Это тоже нужно поправить.

2024-05-24 14:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    Optional<List<Comment>> findAllByItem_Id(Long itemId);
optional необязательно использовать с коллекциями - если элементы не найдены, вернется просто пустая коллекция

2024-05-24 14:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +public class ItemRequestMapper {
предлагаю здесь также использовать mapStruct

2024-05-24 14:38 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@Transactional
эту аннотацию не принято использовать в тестах

2024-05-25 15:08 UTC, facedolls commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +public class ItemRequestMapper {
Исправил.

2024-05-25 15:08 UTC, facedolls commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    Optional<List<Comment>> findAllByItem_Id(Long itemId);
Исправил.

2024-05-27 11:26 UTC, facedolls commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@Transactional
Исправил UserServiceTest, остальные пробую переделать на моки

2024-05-28 14:48 UTC, merged